### PR TITLE
GH-133 Fix working of voice experience system.

### LINKED ISSUE #133: The voice experience is not working properly.

### PR DESCRIPTION
**Pull request by vLuckyyy**
Fixes #133

### CODE REVIEW

**Review by Osnixer — APPROVED** [review]
Looks nice!

File: src/main/java/com/eternalcode/discordapp/leveling/experience/voice/ExperienceLeaveVoiceController.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        long userId = event.getMember().getIdLong();
+
+        LongSupplier voiceLeftChannelId = () -> event.getChannelLeft().getIdLong();
+        this.experienceService.modifyPoints(userId, this.calculatePoints(event), true, voiceLeftChannelId).whenComplete((experience, throwable) -> {
+            if (throwable != null) {
+                throwable.printStackTrace();
+            }
+        });
+
+        this.experienceVoiceActivityData.usersOnVoiceChannel.remove(event.getMember().getIdLong());
```
Comment (imDMK) [inline src/main/java/com/eternalcode/discordapp/leveling/experience/voice/ExperienceLeaveVoiceController.java:43]:
```suggestion
        this.experienceVoiceActivityData.usersOnVoiceChannel.remove(userId);
```

**Review by imDMK — APPROVED** [review]

**Review by Hyd3r1 — CHANGES_REQUESTED** [review]
Only codestyle problem mentioned by DMK, all other looks great! :D

**Review by Jakubk15 — APPROVED** [review]

**Review by Hyd3r1 — APPROVED** [review]
